version: '3'
services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres-container
    restart: always
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      #      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./init.sql:/docker-entrypoint-initdb.d
