ddd:
  context: transtour
---
spring:
  profiles:
    active: h2,mail
---

spring:
  profiles: h2

  datasource:
    driverClassName: org.h2.Driver
    password: sa
    username: sa
    url: jdbc:h2:mem:testdb;INIT=create domain if not exists jsonb as text;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: postgres
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://31.220.61.234:5432/postgres
    username: postgres
    password: ''
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  profiles: mail

  mail:
    host: smtp.gmail.com
    username: pomalianni@gmail.com
    password: newaccount.21
    properties:
      mail:
        smtp:
          auth: true
          port: 25
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp