ddd:
  context: transtour

---
spring:
  profiles: dev-init
  sql:
    init:
      data-locations: classpath:data-dev.sql
      schema-locations: classpath:schema-dev.sql
      mode: always


property:
  schema:
    name : "transtour"
---

spring:
  profiles: preprod-init
  sql:
    init:
      data-locations: classpath:data-preprod.sql
      schema-locations: classpath:schema-preprod.sql
---

web:
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"
---
spring:
  profiles: auditing

  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
            audit_strategy_validity_store_revend_timestamp: true
            store_data_at_delete: true
            default_schema: transtour

---
spring:
  profiles: h2

  datasource:
    driverClassName: org.h2.Driver
    password: sa
    username: sa
    schema: 'transtour'
    url: jdbc:h2:mem:testdb;INIT=create domain if not exists jsonb as text;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_schema: transtour
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: postgres
  sql:
    init:
      mode: NEVER
  datasource:
    password: 'user'
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=transtour&stringtype=unspecified
    username: 'pass'
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


---
spring:
  profiles: mail

  mail:
    host: smtp.gmail.com
    password: ENC(s2Sj+LCCGIpzeNyboZkLC/hPVaJfdpMueqNPUk0+5k8=)
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
          ssl:
            enable: true
    username: ENC(FqmEuzWO0bRUxEefkMqa447q1L5SkfvPSZjiCLTUBVg=)

---
spring:
  profiles: global

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


---

spring:
  profiles: properties
  main:
    allow-bean-definition-overriding: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


---
spring:
  profiles: tc

  security:
    enabled: false
  ignored: /**
  management:
    security:
      enabled: false


  datasource:
    hikari:
      data-source-properties: stringtype=unspecified
    tomcat:
      connection-properties: stringtype=unspecified

    password: 'dbpwd!'
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=transtour&stringtype=unspecified
    username: 'dbadm'
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      default_schema: transtour
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

