ddd:
  context: transtour
---
web:
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"

---
spring:
  profiles: h2

  datasource:
    driverClassName: org.h2.Driver
    password: sa
    username: sa
    url: jdbc:h2:mem:testdb;INIT=create domain if not exists jsonb as text;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: postgres
  sql:
    init:
      mode: always
  datasource:
    url: ENC(0M3iQOQdS1lNBdvLyljP1VLfGCk2mMXv16V40ug0kFGEUNRwydo43HR0PklE/2BIkJQ6We/Arno=)
    username: postgres
    password: ''
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  profiles: mail

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(w10l4gfMQJCQXTQtPAf4vL/aDuTTQSWOhzMbwfjuIVc=)
    password: ENC(s0aAQXWzvEJzGil6A4AcWTkYzYb3rJfS2T2mJq410Yw=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---
spring:
  profiles: global

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    iv-generator-classname: org.jasypt.iv.NoIvGenerator